name: Run integration tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
  
jobs:
  run-test:
    name: Integration tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: D7uli0o71H
          POSTGRESQL_DATABASE: apitest_db

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.20.5
          cache: npm

      - run: npm ci
      - run: npx prisma migrate deploy
        env:
            DATABASE_URL: "postgresql://docker:D7uli0o71H@localhost:5432/apitest_db?schema=public"
            
      - run: npm run test:integration
        env:
          DATABASE_URL: "postgresql://docker:D7uli0o71H@localhost:5432/apitest_db?schema=public"